### PR TITLE
Fixed Seldon golang package

### LINKED ISSUE #1245: Include seldon proto compilation in GO
As per discussion on #1156 for any go application to use use seldon's HTTP/GRPC inference call, it will be helpful if Seldon protos are compiled in GO as part of CI BUILD.

Raising issue for creation of go package for seldon.

### PR DESCRIPTION
**Pull request by hemantkashniyal**
Compiled code for tensorflow and seldon as a GO package

Issue #1156
Fixes #1245 

TODO: need to include `make protos_go` target in CI/CD build @adriangonz

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **cliveseldon**

If they are not already assigned, you can assign the PR to them by writing `/assign @cliveseldon` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Hi @hemantkashniyal. Thanks for your PR.

I'm waiting for a [SeldonIO](https://github.com/orgs/SeldonIO/people) or [seldonio](https://github.com/orgs/seldonio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/seldonio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

File: Makefile [hunk 1]
```diff
@@ -59,3 +59,5 @@ run_python_builder:
 		-v $(SELDON_CORE_LOCAL_DIR):/work \
 		seldonio/python-builder:0.2 bash
 
+protos_go:
+	make -C ./go compile_proto
```
Comment (adriangonz) [inline Makefile]: We tend to keep the root `Makefile` clean, so I'd remove this rule and just call `make -C go compile_proto` directly on the CI/CD pipeline.

File: go/generate_tensorflow_proto.sh [hunk 2]
```diff
@@ -0,0 +1,11 @@
+# set -exv
+rm -rf vendor
+mkdir -p vendor
+git clone https://github.com/tensorflow/tensorflow.git || git --git-dir ./tensorflow/.git pull
```
Comment (adriangonz) [inline go/generate_tensorflow_proto.sh]: Instead of cloning the `tensorflow` repo here, would it make sense to just do the same thing as the `/python/Makefile`'s `get_apis` rule? That way we exploit the existing `/proto/tensorflow/create-protos.sh` script and we also avoid having to clone the entire thing.

https://github.com/SeldonIO/seldon-core/blob/7becc696a34e73f0dce730531c398fd0f0d6fda7/python/Makefile#L7-L11

It would also allow us to just fetch the 4 `*.proto` files we need, instead of having to compile all of the protobufs on the `tensorflow` repo.

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **adriangonz**

If they are not already assigned, you can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

File: go/generate_tensorflow_proto.sh (hunk 2 above)
Comment (hemantkashniyal) [reply go/generate_tensorflow_proto.sh]: @adriangonz agreed tensorflow cloning is not necessary.
Have updated new changes kindly have a look.

File: Makefile (hunk 1 above)
Comment (hemantkashniyal) [reply Makefile]: Sounds fair, have reverted root Makefile

**Comment by hemantkashniyal** [comment]
@adriangonz @cliveseldon it seems `incubating` folder contains go wrappers for preparing s2i image in `go`. That will anyway use these these `seldon go` packages. Is it meant for s2i seldon deployment image support for various languages only?

Moreover these `seldon go` packages will also be used by `go client/apps` doing inference call on `seldon deployment`.  Keeping these initially in `incubating` folder  and later moving to root folder later may break go applications already using this code.

@adriangonz kindly review PR, have incorporated suggestions.

**Comment by hemantkashniyal** [comment]
Hi @adriangonz, can you please review the pull request, I have updated the changes.

**Comment by seldondev** [comment]
Thu Dec 19 10:20:35 UTC 2019
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1246/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1246 --build=1

**Comment by seldondev** [comment]
Thu Dec 19 10:20:37 UTC 2019
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1246/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1246 --build=2

**Comment by cliveseldon** [comment]
Yes might be good to move to `incubating` until we are happy the solution is fully compliant to the python reference standard.

**Comment by adriangonz** [comment]
Got it @cliveseldon! Can you change that @hemantkashniyal? We can think of ways to reduce breaking changes when the Go wrapper is moved from `incubating/` to stable in the future. 

I think after that this PR should be ready to go.

**Comment by seldondev** [comment]
Thu Dec 19 15:14:20 UTC 2019
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1246/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1246 --build=3

**Comment by seldondev** [comment]
Thu Dec 19 15:14:32 UTC 2019
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1246/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1246 --build=4

**Comment by seldondev** [comment]
Thu Dec 19 15:23:57 UTC 2019
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1246/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1246 --build=5

**Comment by seldondev** [comment]
Thu Dec 19 15:24:00 UTC 2019
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1246/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1246 --build=6

**Comment by seldondev** [comment]
Thu Dec 19 15:26:13 UTC 2019
The logs for [pr-build] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1246/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1246 --build=7

**Comment by seldondev** [comment]
Thu Dec 19 15:26:25 UTC 2019
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1246/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1246 --build=8

**Comment by seldondev** [comment]
Thu Dec 19 15:45:13 UTC 2019
The logs for [pr-build] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1246/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1246 --build=9

**Comment by seldondev** [comment]
Thu Dec 19 15:45:25 UTC 2019
The logs for [lint] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1246/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1246 --build=10

**Comment by hemantkashniyal** [comment]
Hi @adriangonz , moved protos to incubating folder. Kindly review PR

**Comment by adriangonz** [comment]
/approve

Awesome! Thanks for your effort and for contributing this work! I think it looks great now!

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1246#issuecomment-567939304" title="Approved">adriangonz</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [adriangonz]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Fri Dec 20 14:18:43 UTC 2019
The logs for [lint] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1246/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1246 --build=12

**Comment by seldondev** [comment]
Fri Dec 20 14:18:55 UTC 2019
The logs for [pr-build] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1246/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1246 --build=11
