### PR TITLE
Fix clean up of old virtual services

### LINKED ISSUE #1594: Duplicated VirtualServices entries
Using Istio, the operator seems to be creating duplicated `VirtualService` entries after updating some `SeldonDeployments`. Since both entries try to map the same URL, the result is that trying to access it will return in a **503 error**.

For a `SeldonDeployment` called `my-model-name`, the only differences between both seem to be:

- The service name in `Route.Destination.Host` changes between them. The old `VirtualService` points to a service name called `seldon-<hash>`, whereas the newer one points to `my-model-name`.
- The name of the `VirtualService` are also different. The old one is called `my-model-name-my-model-name-http`, whereas the new one is simply called `my-model-name-http`.

Maybe related to #1461?

### PR DESCRIPTION
**Pull request by cliveseldon**
Fixes #1594

 * Adds a new cleaner function that looks for owned virtual services and compares to expected and deletes any extra

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **cliveseldon**

If they are not already assigned, you can assign the PR to them by writing `/assign @cliveseldon` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Thu Mar 26 18:38:44 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1618/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1618 --build=1

**Comment by seldondev** [comment]
Thu Mar 26 18:38:49 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1618/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1618 --build=2

**Comment by seldondev** [comment]
Thu Mar 26 20:16:09 UTC 2020
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1618/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1618 --build=3

**Comment by seldondev** [comment]
Fri Mar 27 11:03:41 UTC 2020
The logs for [lint] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1618/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1618 --build=5

**Comment by seldondev** [comment]
Fri Mar 27 11:03:42 UTC 2020
The logs for [pr-build] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1618/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1618 --build=4

File: operator/controllers/seldondeployment_controller.go [hunk 1]
```diff
@@ -950,19 +943,23 @@ func (r *SeldonDeploymentReconciler) createIstioServices(components *components,
...
 
+	//Cleanup unused VirtualService. This should usually only happen on Operator upgrades where there is a breaking change to the names of the VirtualServices created
+	if ready {
+		cleaner := ResourceCleaner{instance: instance, client: r, virtualServices: components.virtualServices, logger: r.Log}
+		deleted, err := cleaner.cleanUnusedVirtualServices()
+		if err != nil {
+			return ready, err
+		}
+		for _, vsvcDeleted := range deleted {
+			r.Recorder.Eventf(instance, corev1.EventTypeNormal, constants.EventsDeleteVirtualService, "Delete VirtualService %q", vsvcDeleted.GetName())
```
Comment (adriangonz) [inline operator/controllers/seldondeployment_controller.go]: nit: on the event message, should we say `Deleted` instead of `Delete`?

File: operator/controllers/seldondeployment_controller_test.go [hunk 2]
```diff
@@ -711,6 +711,118 @@ var _ = Describe("Create a Seldon Deployment and then a new one", func() {
...
+			},
+		}
+
+		//Create namespace
+		namespace := &v1.Namespace{
+			ObjectMeta: metav1.ObjectMeta{
+				Name: namespaceName,
+			},
+		}
+		Expect(k8sClient.Create(context.Background(), namespace)).Should(Succeed())
```
Comment (adriangonz) [inline operator/controllers/seldondeployment_controller_test.go]: We could probably move most of this setup (e.g. creating the namespace, defining a `SeldonDeployment` spec, setting default timeouts, etc.) into a `BeforeEach` block shared by all the tests in `operator/controllers/seldondeployment_controller_test.go`.

This is just a thought though and it probably falls outside the scope of this PR, so feel free to ignore.

**Comment by seldondev** [comment]
Fri Mar 27 13:29:46 UTC 2020
The logs for [integration] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1618/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1618 --build=6

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 729b6864163df390a30e573dd27374e51ee06726 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Sat Mar 28 14:30:37 UTC 2020
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1618/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1618 --build=8

**Comment by seldondev** [comment]
Sat Mar 28 14:30:40 UTC 2020
The logs for [pr-build] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1618/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1618 --build=7

**Comment by seldondev** [comment]
Sat Mar 28 14:32:50 UTC 2020
The logs for [integration] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1618/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1618 --build=9

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 729b6864163df390a30e573dd27374e51ee06726 | [link]() | `/test integration`
pr-build | f74bb6303e37229c2942a186fdc12025abf8396c | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Sat Mar 28 18:31:34 UTC 2020
The logs for [lint] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1618/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1618 --build=11

**Comment by seldondev** [comment]
Sat Mar 28 18:31:34 UTC 2020
The logs for [pr-build] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1618/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1618 --build=10

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | f74bb6303e37229c2942a186fdc12025abf8396c | [link]() | `/test this`
lint | 67824bba7bb1ef7e6e92410ceccb55a4f46c7217 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Sat Mar 28 19:04:24 UTC 2020
The logs for [lint] [13] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1618/13.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1618 --build=13

**Comment by seldondev** [comment]
Sat Mar 28 19:04:25 UTC 2020
The logs for [pr-build] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1618/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1618 --build=12

**Comment by seldondev** [comment]
Sat Mar 28 19:05:11 UTC 2020
The logs for [notebooks] [14] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1618/14.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1618 --build=14

**Comment by seldondev** [comment]
Sun Mar 29 08:16:43 UTC 2020
The logs for [pr-build] [15] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1618/15.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1618 --build=15

**Comment by seldondev** [comment]
Sun Mar 29 08:16:48 UTC 2020
The logs for [lint] [16] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1618/16.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1618 --build=16

**Comment by seldondev** [comment]
Sun Mar 29 08:23:36 UTC 2020
The logs for [notebooks] [17] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1618/17.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1618 --build=17

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 46b9487a3bce3e1675ed2049da5fb3c6dbc53831 | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | f3c598c54ac696e3b9680e6ee92be51e5485c05c | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Sun Mar 29 10:42:14 UTC 2020
The logs for [lint] [19] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1618/19.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1618 --build=19

**Comment by seldondev** [comment]
Sun Mar 29 10:42:32 UTC 2020
The logs for [pr-build] [18] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1618/18.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1618 --build=18

**Comment by seldondev** [comment]
Sun Mar 29 10:50:34 UTC 2020
The logs for [notebooks] [20] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1618/20.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1618 --build=20

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | ca67edadd15a90a559a703420f065e448b9eff31 | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Sun Mar 29 14:02:29 UTC 2020
The logs for [integration] [21] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1618/21.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1618 --build=21
