### PR TITLE
Fix content-type behaviour in executor

### LINKED ISSUE #1899: Multipart form data not passed between chain of seldon components
Hi,
I just found that form data is not passed from one seldon component to another. I have tried passing normal data of content-type "application/json" between components and it works fine,but form data doesnt seem to be transfered between seldon components.

I have two programs,one  has input transformer and the other has model component. I have used transform_input_raw and predict_raw methods. I pass an audio file input with keyword "binData" . I am able to process the input in transformer and the input passed can be seen in logs...The transformer returns a dictionary containing the binary data which is to be received as input by the predict method in model.py file.But the model receives an empty dictionary and throws a key error.
PFA the method used in 2 program screenshots

image

image

Someone please do look into this and do reply

### PR DESCRIPTION
**Pull request by cliveseldon**
Fixes #1899 

Ensure:

 * `Content-Type` passed in initial request is used for initial component REST call
 * `Content-Type` from responses in the graph are used for next request
 * Adding headers to each request from initial headers does not overwrite `Content-Type`

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **cliveseldon**

If they are not already assigned, you can assign the PR to them by writing `/assign @cliveseldon` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Sat May 30 15:36:23 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1900/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1900 --build=2

**Comment by seldondev** [comment]
Sat May 30 15:37:38 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1900/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1900 --build=1

**Comment by seldondev** [comment]
Sun May 31 07:08:55 UTC 2020
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1900/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1900 --build=3

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | edfeeaece8979e68c0fe5c80faca187cb3f45ab8 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Sun May 31 08:55:46 UTC 2020
The logs for [notebooks] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1900/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1900 --build=4

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | edfeeaece8979e68c0fe5c80faca187cb3f45ab8 | [link]() | `/test integration`
notebooks | edfeeaece8979e68c0fe5c80faca187cb3f45ab8 | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Sun May 31 15:28:24 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1900/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1900 --build=5

**Comment by seldondev** [comment]
Sun May 31 15:28:23 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1900/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1900 --build=6

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | edfeeaece8979e68c0fe5c80faca187cb3f45ab8 | [link]() | `/test integration`
notebooks | edfeeaece8979e68c0fe5c80faca187cb3f45ab8 | [link]() | `/test notebooks`
lint | 910df1cd49ac65e8c0669e4e7577f1ca25010707 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Sun May 31 15:29:54 UTC 2020
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1900/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1900 --build=8

**Comment by seldondev** [comment]
Sun May 31 15:30:01 UTC 2020
The logs for [pr-build] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1900/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1900 --build=7

**Comment by seldondev** [comment]
Sun May 31 16:26:20 UTC 2020
The logs for [integration] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1900/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1900 --build=9

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | edfeeaece8979e68c0fe5c80faca187cb3f45ab8 | [link]() | `/test notebooks`
integration | 51cb5807b08b285617fda2091a023e07379cdc54 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Jun  1 07:42:42 UTC 2020
The logs for [integration] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1900/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1900 --build=10

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | edfeeaece8979e68c0fe5c80faca187cb3f45ab8 | [link]() | `/test notebooks`
integration | 51cb5807b08b285617fda2091a023e07379cdc54 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Jun  1 10:25:47 UTC 2020
The logs for [integration] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1900/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1900 --build=11

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | edfeeaece8979e68c0fe5c80faca187cb3f45ab8 | [link]() | `/test notebooks`
integration | 51cb5807b08b285617fda2091a023e07379cdc54 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Jun  2 08:13:36 UTC 2020
The logs for [notebooks] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1900/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1900 --build=12

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 51cb5807b08b285617fda2091a023e07379cdc54 | [link]() | `/test integration`
notebooks | 51cb5807b08b285617fda2091a023e07379cdc54 | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Jun  2 14:13:12 UTC 2020
The logs for [notebooks] [13] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1900/13.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1900 --build=13

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 51cb5807b08b285617fda2091a023e07379cdc54 | [link]() | `/test integration`
notebooks | 51cb5807b08b285617fda2091a023e07379cdc54 | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Jun 16 16:51:42 UTC 2020
The logs for [lint] [15] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1900/15.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1900 --build=15

**Comment by seldondev** [comment]
Tue Jun 16 16:51:43 UTC 2020
The logs for [pr-build] [14] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1900/14.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1900 --build=14

**Comment by seldondev** [comment]
Tue Jun 16 17:10:39 UTC 2020
The logs for [integration] [16] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1900/16.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1900 --build=16

**Comment by seldondev** [comment]
Tue Jun 16 19:44:04 UTC 2020
The logs for [notebooks] [17] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1900/17.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1900 --build=17

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 51cb5807b08b285617fda2091a023e07379cdc54 | [link]() | `/test notebooks`
integration | 0e21a1096fa196cacc425a3029a7d0a4161851b1 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 0e21a1096fa196cacc425a3029a7d0a4161851b1 | [link]() | `/test integration`
notebooks | 0e21a1096fa196cacc425a3029a7d0a4161851b1 | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Jun 16 21:45:13 UTC 2020
The logs for [lint] [19] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1900/19.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1900 --build=19

**Comment by seldondev** [comment]
Tue Jun 16 21:45:18 UTC 2020
The logs for [pr-build] [18] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1900/18.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1900 --build=18

**Comment by seldondev** [comment]
Tue Jun 16 21:46:19 UTC 2020
The logs for [integration] [20] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1900/20.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1900 --build=20

**Comment by seldondev** [comment]
Wed Jun 17 06:32:48 UTC 2020
The logs for [notebooks] [21] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1900/21.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1900 --build=21

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 31a5c8ec2f2a2893389e666776e54235ed0d5c1e | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

File: executor/api/rest/client.go [hunk 1]
```diff
@@ -139,24 +142,26 @@ func (smc *JSONRestClient) getMetricsRoundTripper(modelName string, service stri
 
 func (smc *JSONRestClient) addHeaders(req *http.Request, m map[string][]string) {
 	for k, vv := range m {
-		for _, v := range vv {
-			req.Header.Set(k, v)
+		if _, ok := headersIgnore[k]; !ok {
+			for _, v := range vv {
+				req.Header.Set(k, v)
```
Comment (adriangonz) [inline executor/api/rest/client.go:147]: If `vv` is a list of values, won't [`req.Header.Set`](https://golang.org/pkg/net/http/#Header.Set) override each previous entry and just leave the latest one? We may need to use [`req.Header.Add`](https://golang.org/pkg/net/http/#Header.Add) instead.

File: executor/api/rest/client.go [hunk 2]
```diff
@@ -139,24 +142,26 @@ func (smc *JSONRestClient) getMetricsRoundTripper(modelName string, service stri
...
 
-func (smc *JSONRestClient) doHttp(ctx context.Context, modelName string, method string, url *url.URL, msg []byte, meta map[string][]string) ([]byte, string, error) {
+func (smc *JSONRestClient) doHttp(ctx context.Context, modelName string, method string, url *url.URL, msg []byte, meta map[string][]string, contentType string) ([]byte, string, error) {
 	smc.Log.Info("Calling HTTP", "URL", url)
 
 	var req *http.Request
 	var err error
 	if msg != nil {
-		smc.Log.Info("Building message")
+		smc.Log.Info("Building message", "contentType", contentType, "msg", string(msg))
```
Comment (adriangonz) [inline executor/api/rest/client.go:159]: Is it possible to ignore `INFO` level in the logs atm? I'm just wondering whether we should remove `msg` until we confirm that point (to avoid making it extra verbose).

Comment (cliveseldon) [reply executor/api/rest/client.go:159]: I'll remove these

File: executor/api/rest/client.go (hunk 1 above)
Comment (cliveseldon) [reply executor/api/rest/client.go:147]: Yes. Change to Add

**Comment by seldondev** [comment]
Wed Jun 17 09:55:38 UTC 2020
The logs for [lint] [23] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1900/23.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1900 --build=23

**Comment by seldondev** [comment]
Wed Jun 17 09:55:49 UTC 2020
The logs for [pr-build] [22] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1900/22.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1900 --build=22

**Comment by seldondev** [comment]
Wed Jun 17 09:56:19 UTC 2020
The logs for [integration] [24] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1900/24.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1900 --build=24

**Comment by axsaucedo** [comment]
Looks good!

File: executor/api/rest/client.go (hunk 1 above)
Comment (adriangonz) [reply executor/api/rest/client.go]: Does it work with the first one? You've got tests in there, so I guess it does work!

**Comment by adriangonz** [comment]
Looks good from my side @cliveseldon ! Should be good to land once the integration tests pass. :crossed_fingers:

**Comment by axsaucedo** [comment]
All integration tests pass 🚀
/approve

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1900#issuecomment-645333184" title="Approved">axsaucedo</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Wed Jun 17 12:07:30 UTC 2020
The logs for [lint] [26] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1900/26.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1900 --build=26

**Comment by seldondev** [comment]
Wed Jun 17 12:07:50 UTC 2020
The logs for [pr-build] [25] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1900/25.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1900 --build=25
